import type { Metadata } from "next";
import { Inter } from "next/font/google";
 

import "./globals.css";
import { Sidebar } from "./(dashboard)/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
   
      <html lang="en">
        <body className={inter.className}>
     
        <div className="bg-muted h-full">
      <Sidebar />
      <div className="lg:pl-[300px] flex flex-col h-full">
        {/* <Navbar /> */}
        <main className="bg-white flex-1 overflow-auto p-8 lg:rounded-tl-2xl">
          {children}
        </main>
      </div>
    </div>
          
        </body>
      </html>
  
  );
}
